Updated config and gen_version.sh scripts to match GRSIData

diff --git a/util/config b/util/config
--- a/util/config
+++ b/util/config
@@ -1,30 +1,29 @@
 #!/usr/bin/env bash 
 
 readlink=readlink
-if [ `uname` = "AIX" ]; then
-  readlink=echo
+if [ "$(uname)" = "AIX" ]; then
+  readlink="echo"
 fi
 
 # work around readlink versions not having -f option
-fullpath1=`$readlink $0`
-if [ "$?" -ne "0" ]; then
-  fullpath1=$0
+if ! fullpath1=$($readlink "$0"); then
+  fullpath1="$0"
 else
-  if [ ${fullpath1##/} = $fullpath1 ] && [ ${fullpath1##~} = $fullpath1 ]; then
+  if [ "${fullpath1##/}" = "$fullpath1" ] && [ "${fullpath1##~}" = "$fullpath1" ]; then
     # relative path, prepend directory where executable was found
-    lpath=`dirname $0`
+    lpath=$(dirname "$0")
     fullpath1=$lpath/$fullpath1
   fi
 fi
 
-progdir=`dirname $fullpath1`
-runningdir=`pwd`
-if [ ${progdir##/} != $progdir ] || [ ${progdir##~} != $progdir ]; then
+progdir=$(dirname "$fullpath1")
+runningdir=$(pwd)
+if [ "${progdir##/}" != "$progdir" ] || [ "${progdir##~}" != "$progdir" ]; then
   # absolute path
   fullpath=$progdir
 else
   # relative path
-  if [ $progdir != "." ]; then
+  if [ "$progdir" != "." ]; then
     fullpath=$runningdir/$progdir
   else
     fullpath=$runningdir
@@ -32,16 +31,31 @@ else
 fi
 
 # work around readlink versions not having -f option
-fullpath1=`$readlink $fullpath`
-if [ "$?" -ne "0" ]; then
+if ! fullpath1=$($readlink "$fullpath"); then
   fullpath1=$fullpath
 fi
 
+if [ -d "${GRSISYS}/iThembaData/lib" ] ; then
+	libdir="${GRSISYS}/iThembaData/lib"
+elif [ -d "${GRSISYS}/lib" ] ; then
+	libdir="${GRSISYS}/lib"
+else
+	echo "Couldn't find either $GRSISYS/iThembaData/lib or $GRSISYS/lib directory, not sure what to do"
+	exit
+fi
+if [ -d "${GRSISYS}/iThembaData/include" ] ; then
+	incdir="${GRSISYS}/iThembaData/include"
+elif [ -d "${GRSISYS}/include" ] ; then
+	incdir="${GRSISYS}/include"
+else
+	echo "Couldn't find either ${GRSISYS}/iThembaData/include or ${GRSISYS}/include directory, not sure what to do"
+	exit
+fi
 
-libdir=$GRSISYS/iThembaData/lib
-incdir=$GRSISYS/iThembaData/include
+libdir="${GRSISYS}/iThembaData/lib"
+incdir="${GRSISYS}/iThembaData/include"
 
-libs="-lTTdrClover -lTTdrPlastic -lTTdrSiLi -lTTdrTigress"
+libs="TTdrClover TTdrPlastic TTdrSiLi TTdrTigress"
 
 if [[ $(root-config --cflags) == *"-std="* ]]
 then
@@ -65,48 +79,64 @@ cflagsout=no
 libsout=no
 
 while test $# -gt 0; do
-  case "$1" in 
-  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
-  *)    optarg= ;;
-  esac
-
   case $1 in
     --version)
       ### Output the version number.  If GVersion.h can not be found, give up.
-      if test -r ${incdir}/GVersion.h; then
-        out="$out `sed -n 's,.*GRSI_RELEASE *\"\(.*\)\".*,\1,p' < ${incdir}/GVersion.h`"
+      if test -r "${incdir}/GVersion.h"; then
+        tmp=$(sed -n 's,.*GRSI_RELEASE *\"\(.*\)\".*,\1,p' < "${incdir}/GVersion.h")
+        out="$out $tmp"
       else
         echo "cannot read ${incdir}/GVersion.h"
         exit 1
       fi
       ;;
     --incdir)
-      if test "x$incdirout" = "xyes" ; then
+      if test "$incdirout" = "yes" ; then
         shift
         continue
       fi
       incdirout="yes"
-      out="$out $incdir "
+		if [ -z "$out" ] ; then
+			out="$incdir"
+		else
+			out="$out $incdir "
+		fi
       ;;
     --cflags)
-      if test "x$cflagsout" = "xyes" ; then
+      if test "$cflagsout" = "yes" ; then
         shift
         continue
       fi
       cflagsout="yes"
-      out="$out $cflags "
+		if [ -z "$out" ] ; then
+			out="$cflags"
+		else
+			out="$out $cflags "
+		fi
       ;;
     --libs)
-      if test "x$libsout" = "xyes" ; then
+      if test "$libsout" = "yes" ; then
         shift
         continue
       fi
       libsout="yes"
-      out=$"$out -L${libdir} $libs "
+		if [ -d "${libdir}" ] ; then
+			if [ -z "$out" ] ; then
+				out="-L${libdir}"
+			else
+				out="$out -L${libdir}"
+			fi
+		fi
+		for library in $libs ; do
+			if [ -e "${libdir}/lib${library}.so" ] || [ -e "${libdir}/lib${library}.dylib" ] ; then
+				out="$out -l${library}"
+			fi
+		done
       ;;
     --help)
       ### Print a helpful message...
-      echo "Usage: `basename $0` [options]"
+      progname=$(basename "$0")
+      echo "Usage: ${progname} [options]"
       echo ""
       echo "  --version       Print the current GRSI Version number."
       echo "  --incdir        Print header path."
@@ -118,12 +148,12 @@ while test $# -gt 0; do
     *)
       ### Give an error
       echo "Unknown argument \"$1\"!" 1>&2
-      echo "${usage}" 1>&2
+      echo "$usage" 1>&2
       exit 1
       ;;
    esac
    shift 
 done
 
-echo $out
+echo "$out"
 
